name: Klipper_Compile_Binaries

on:
  push:
    branches:
      - main
    paths:
      - 'trigger.md'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Enable Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check out 3Dwork Auto Builder Repo repo
        uses: actions/checkout@v4
        with:
          # repository: Klipper3d/klipper
          github-server-url: https://github.com/Klipper3d/klipper.git
          path: /home/runner/work/klipper_auto_builder_3dwork/klipper_auto_builder_3dwork

      - name: Shows files content
        run: |
          ls ${{ github.workspace }}

      - name: Install Klipper
        run: | 
          ./klipper/scripts/install-ubuntu-22.04.sh

      - name: Check out 3Dwork Auto Builder Repo repo
        uses: actions/checkout@v4

