name: Klipper_Compile_Binaries

on:
  push:
    branches:
      - main
    paths:
      - 'trigger.md'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest
    env:
      BOARD: sanguino1284p_optimized

    steps:
      - name: Check out repo
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Clone Klipper
        run: | 
          git clone https://github.com/Klipper3d/klipper
          ./klipper/scripts/install-ubuntu-2204.sh

