name: Klipper_Compile_Binaries

on:
  push:
    branches:
      - main
    paths:
      - 'trigger.md'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Enable Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check out Klipper repo
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: ${{ github.workspace }}/klipper

      - name: Install Klipper
        run: | 
          chmod +x ${{ github.workspace }}/klipper/scripts/*.sh
          ${{ github.workspace }}/klipper/scripts/install-ubuntu-22.04.sh

      - name: Check out 3Dwork Auto Builder Repo repo
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/3dwork
        
      - name: Compile Klipper Firmware for Boards
        run: | 
          chmod +x ${{ github.workspace }}/3dwork/compile-binaries.sh
          ${{ github.workspace }}/3dwork/compile-binaries.sh

      - name: Shows files content
        run: |
          ls -R

      - name: Push Compiled Klipper Firmwares
        run: |
          cd ${{ github.workspace }}/3dwork
          git config --global user.name "JJR Bot"
          git config --global user.email "jrodriguez@qitec.net"
          git pull origin master --ff-only
          git add .
          git commit -m "Compiled firmware"
          git push "https://${{ github.actor }}:${{ secrets.COMMIT_TOKEN }}@github.com/${{ github.repository }}.git"
      


