name: Klipper_Compile_Binaries

on:
  push:
    branches:
      - main
    paths:
      - 'trigger.md'
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_push:
    name: Compile and Push Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Enable Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check out Klipper repo
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: ${{ github.workspace }}/klipper

      - name: Install Klipper
        run: | 
          chmod +x ${{ github.workspace }}/klipper/scripts/*.sh
          ${{ github.workspace }}/klipper/scripts/install-ubuntu-22.04.sh

      - name: Check out 3Dwork Auto Builder Repo repo
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: ${{ github.workspace }}/3dwork
        
      - name: Install Klipper
        run: | 
          chmod +x ${{ github.workspace }}/3dwork/compile-binaries.sh
          ${{ github.workspace }}/3dwork/compile-binaries.sh
      
      - name: Shows files content
        run: |
          ls -R

